# Generated by Django 4.1.5 on 2023-01-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="food_photos/"),
        ),
        migrations.AddField(
            model_name="food",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="food_videos/"),
        ),
    ]
