# Generated by Django 4.1.5 on 2023-01-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_food_photo_food_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="photo",
            field=models.ImageField(blank=True, upload_to="food_photos/"),
        ),
        migrations.AlterField(
            model_name="food",
            name="video",
            field=models.FileField(blank=True, upload_to="food_videos/"),
        ),
    ]
